"""Nullable false for title and context

Revision ID: ddb74b6a3230
Revises: c41283d68da0
Create Date: 2026-03-05 12:21:46.881664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ddb74b6a3230"
down_revision: Union[str, Sequence[str], None] = "c41283d68da0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts", "content", existing_type=sa.VARCHAR(length=250), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts", "content", existing_type=sa.VARCHAR(length=250), nullable=True
    )
    # ### end Alembic commands ###
