"""Delete name + surname and add email + username fields

Revision ID: c41283d68da0
Revises: ee8035c7beee
Create Date: 2026-03-05 09:58:50.932139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c41283d68da0"
down_revision: Union[str, Sequence[str], None] = "ee8035c7beee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.add_column("users", sa.Column("username", sa.String(length=20), nullable=False))
    op.drop_column("users", "name")
    op.drop_column("users", "surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "surname", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "username")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
